app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home' ),
    path('contact/', views.ContactView.as_view(), name="contact" ),
    path('cart/', include('cart.urls', namespace="cart" )),
    path('accounts/', include('allauth.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='summary'),
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('increase-quantity/<pk>/', views.IncreaseQuantityView.as_view(), name="increase-quantity"  ),
    path('decrease-quantity/<pk>/', views.DecreaseQuantityView.as_view(), name="decrease-quantity"  ),
    path('remove-from-cart/<pk>/', views.RemoveFromCartView.as_view(), name="remove-from-cart"  ),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('thank-you/', views.ThankYouView.as_view(), name='thank-you' ),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order' ), 
]

cart/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.shortcuts import reverse

User = get_user_model()

class Address(models.Model):
    
    ADRESS_CHOICES = (
        ('B', 'Billing'),
        ('S', 'Shipping'),
    )
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    adress_line_1 = models.CharField(max_length=120)
    
    adress_line_2 = models.CharField(max_length=120)
    
    city = models.CharField(max_length=120)
    
    zip_code = models.CharField(max_length=120)
    
    
    adress_type = models.CharField(max_length=1, choices= ADRESS_CHOICES  )
    
    default = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.adress_line_1}, {self.adress_line_2}, {self.city}, {self.zip_code}"
    
    
    class Meta:
        verbose_name_plural = 'Addresses'
        

class ColourVariation(models.Model):
    
    name = models.CharField(max_length=120)
    
    def __str__(self):
        
        return self.name
    
class SizeVariation(models.Model):
    
    name = models.CharField(max_length=120)
    
    def __str__(self):
        
        return self.name
        

class Product(models.Model):
    
    title = models.CharField(max_length=50)
    
    slug = models.SlugField(unique=True)
    
    image = models.ImageField(upload_to='product_images')
    
    description = models.TextField()
    
    price = models.IntegerField(default=0)
    
    created = models.DateTimeField(auto_now_add=True)
    
    updated = models.DateTimeField(auto_now=True)
    
    active = models.BooleanField(default=False)
    
    available_colours = models.ManyToManyField(ColourVariation)
    
    available_sizes = models.ManyToManyField(SizeVariation)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("cart:product-detail", kwargs={"slug": self.slug})
    
    def get_price(self):
        return "{:.2f}".format(self.price / 100)
    


class OrderItem(models.Model):
    
    order = models.ForeignKey('Order', related_name="items", on_delete=models.CASCADE)
    
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    
    quantity = models.PositiveIntegerField(default=1)
    
    colour = models.ForeignKey(ColourVariation, on_delete=models.CASCADE)
    
    size = models.ForeignKey(SizeVariation, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.quantity} x {self.product.title}"
    
    def get_raw_total_item_price(self):
        return self.quantity * self.product.price 
    
    def get_total_item_price(self):
        
        price = self.get_raw_total_item_price() 
        
        return "{:.2f}".format(price / 100)



class Order(models.Model):
    
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    
    start_date = models.DateTimeField(auto_now_add=True)
    
    order_date = models.DateTimeField(blank=True, null=True)
    
    ordered = models.BooleanField(default=False)
    
    billing_address = models.ForeignKey(Address, related_name="billing_address", 
                                    on_delete=models.SET_NULL, blank=True, null=True)
    
    shipping_address = models.ForeignKey(Address, related_name="shipping_address", 
                                    on_delete=models.SET_NULL, blank=True, null=True)
    
    def __str__(self):
        return self.reference_number
    
    @property
    def reference_number(self):
        return f"ORDER-{self.pk}"
    
    def get_raw_subtotal(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_raw_total_item_price()
            
        return total
    
    def get_subtotal(self):
        subtotal = self.get_raw_subtotal()
        return "{:.2f}".format(subtotal / 100)
    
    def get_raw_total(self):
        subtotal = self.get_raw_subtotal()
        #agregar suma de igv impuestos 
        # total = subtotal - discounts + tax + delivery 
        return subtotal
    
    def get_total(self):
        total = self.get_raw_total()
        return "{:.2f}".format(total / 100)
    
    
    
class Payment(models.Model):
    
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="payments"  )
    
    payment_method = models.CharField(max_length=20, choices=(
        ('Paypal', 'Paypal'),
    ))
    
    timestamp = models.DateTimeField(auto_now_add=True)
    
    succesful = models.BooleanField(default=False)
    
    mount = models.FloatField()
    
    row_response = models.TextField()
    
    def __str__(self):
        return self.reference_number
    
    @property
    def reference_number(self):
        return f"PAYMENT-{self.order}-{self.pk}"
    
     

def pre_save_product_receiver(sender, instance, *args, **kwargs ):
    if not instance.slug:
        instance.slug = slugify(instance.title)
        
pre_save.connect(pre_save_product_receiver, sender=Product)

cart/forms.py
from django import forms
from .models import OrderItem, Product, ColourVariation, SizeVariation, Address
from django.contrib.auth import get_user_model

User = get_user_model()

class AddToCartForm(forms.ModelForm):
    
    colour = forms.ModelChoiceField(queryset=ColourVariation.objects.none() )
    
    size = forms.ModelChoiceField(queryset=SizeVariation.objects.none() )
    
    
    class Meta:
        
        model = OrderItem
        
        fields = ['quantity', 'colour', 'size'] 
        
        
    def __init__(self, *args, **kwargs ):
        
        product_id = kwargs.pop('product_id')
        
        product = Product.objects.get(id=product_id)
        
        super().__init__(*args, **kwargs)
        
        self.fields['colour'].queryset = product.available_colours.all()
        
        self.fields['size'].queryset = product.available_sizes.all()
        
class AddressForm(forms.Form):

    shipping_address_line_1 = forms.CharField(required=False)
    
    shipping_address_line_2 = forms.CharField(required=False)
    
    shipping_zip_code = forms.CharField(required=False)
    
    shipping_city = forms.CharField(required=False)
    
    
    billing_address_line_1 = forms.CharField(required=False)
    
    billing_address_line_2 = forms.CharField(required=False)
    
    billing_zip_code = forms.CharField(required=False)
    
    billing_city = forms.CharField(required=False)
    
    
    selected_shipping_address = forms.ModelChoiceField(
        Address.objects.none(), required=False
    )
    
    selected_billing_address = forms.ModelChoiceField(
        Address.objects.none(), required=False
    )
    
    def __init__(self, *args, **kwargs ):
        
        user_id = kwargs.pop('user_id')
        
        super().__init__(*args, **kwargs)
        
        user = User.objects.get(id = user_id)
        
        shipping_address_qs = Address.objects.filter(
            user = user,
            adress_type = 'S',
        )
        
        billing_address_qs = Address.objects.filter(
            user = user,
            adress_type = 'B',
        )
        
        self.fields['selected_shipping_address'].queryset = shipping_address_qs 
        
        self.fields['selected_billing_address'].queryset = billing_address_qs 
        
        
    def clean(self):
    
        data = self.cleaned_data
        
        
        selected_shipping_address = data.get('selected_shipping_address', None)
        
        if selected_shipping_address is None:
            
            if not data.get('shipping_address_line_1', None ):
                self.add_error('shipping_address_line_1', "please fill in this field")
                
            if not data.get('shipping_address_line_2', None ):
                self.add_error('shipping_address_line_2', "please fill in this field")
                
            if not data.get('shipping_zip_code', None ):
                self.add_error('shipping_zip_code', "please fill in this field")
                
            if not data.get('shipping_city', None ):
                self.add_error('shipping_city', "please fill in this field")   
                
        
        selected_billing_address = data.get('selected_billing_address', None)
        
        if selected_billing_address is None:
            
            if not data.get('billing_address_line_1', None ):
                self.add_error('billing_address_line_1', "please fill in this field")
                
            if not data.get('billing_address_line_2', None ):
                self.add_error('billing_address_line_2', "please fill in this field")
                
            if not data.get('billing_zip_code', None ):
                self.add_error('billing_zip_code', "please fill in this field")
                
            if not data.get('billing_city', None ):
                self.add_error('billing_city', "please fill in this field") 

cart/views.py
from datetime import datetime
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views import generic
from .models import Product, OrderItem, Address, Payment
from .utils import get_or_set_order_session
from django.shortcuts import get_object_or_404, reverse, redirect
from .forms import AddToCartForm, AddressForm
from django.contrib import messages
from django.conf import settings
import json



class ProductListView(generic.ListView):
    
    template_name = 'cart/product_list.html'
    
    queryset = Product.objects.all()
    
    
    
class ProductDetailView(generic.FormView):
    
    template_name = 'cart/product_detail.html'
    
    form_class = AddToCartForm
    
    def get_object(self):
        return get_object_or_404(Product, slug=self.kwargs['slug'])
    
    def get_success_url(self):
        return reverse('cart:summary')
    
    def get_form_kwargs(self):
        
        kwargs = super(ProductDetailView, self).get_form_kwargs()
        
        kwargs['product_id'] = self.get_object().id
                
        return kwargs
        
            
    def form_valid(self, form):
        
        order = get_or_set_order_session(self.request) 
        
        product = self.get_object()
        
        item_filter = order.items.filter(
            product=product, 
            colour=form.cleaned_data['colour'],
            size= form.cleaned_data['size']
            )
        
        if item_filter.exists():
            
            item = item_filter.first()
            
            item.quantity += int(form.cleaned_data['quantity'])
            
            item.save()
            
        else:
            
            new_item = form.save(commit=False)
            
            new_item.product = product
            
            new_item.order = order
            
            new_item.save()
        
        return super(ProductDetailView, self).form_valid(form)
    
     
    
    def get_context_data(self, **kwargs):
        
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        
        context ['product'] = self.get_object()
        
        return context
    


class CartView(generic.TemplateView):
    
    template_name = 'cart/cart.html'
    
    def get_context_data(self, *args, **kwargs ):
        
        context = super(CartView, self).get_context_data(*args, **kwargs)
        
        context['order'] = get_or_set_order_session(self.request)
        
        return context



class IncreaseQuantityView(generic.View):
    
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk']) 
        order_item.quantity += 1
        order_item.save()
        return redirect("cart:summary")
  
    
    
class DecreaseQuantityView(generic.View):
    
    def get(self, request, *args, **kwargs):
        
        order_item = get_object_or_404(OrderItem, id=kwargs['pk']) 
        
        if order_item.quantity <= 1:
            
            order_item.delete()
        
        else:
            
            order_item.quantity -= 1
        
            order_item.save()
        
        return redirect("cart:summary")
    
    
    
class RemoveFromCartView(generic.View):
    
    
    def get(self, request, *args, **kwargs):
        
        order_item = get_object_or_404(OrderItem, id=kwargs['pk']) 
        
        order_item.delete()
        
        return redirect("cart:summary")
    
    
    
class CheckoutView(generic.FormView):
    
    template_name = 'cart/checkout.html'
    
    form_class = AddressForm
    
    def get_success_url(self):
        
        return reverse("cart:payment")
    
    
    def form_valid(self, form):
        
        order = get_or_set_order_session(self.request)
        
        selected_shipping_address = form.cleaned_data.get('selected_shipping_address ')
        
        selected_billing_address = form.cleaned_data.get('selected_billing_address ')
        
        if selected_shipping_address:
            
            order.shipping_address = selected_shipping_address
            
        else:
            
            address = Address.objects.create(
                adress_type = 'S',
                user = self.request.user,
                adress_line_1= form.cleaned_data['shipping_address_line_1'],
                adress_line_2= form.cleaned_data['shipping_address_line_2'],
                zip_code= form.cleaned_data['shipping_zip_code'],
                city= form.cleaned_data['shipping_city'],
                
            )
            
            order.shipping_address = address
    
        
        
        if selected_billing_address:
            
            order.billing_address = selected_billing_address
            
        else:
            
            address = Address.objects.create(
                adress_type = 'B',
                user = self.request.user,
                adress_line_1= form.cleaned_data['billing_address_line_1'],
                adress_line_2= form.cleaned_data['billing_address_line_2'],
                zip_code= form.cleaned_data['billing_zip_code'],
                city= form.cleaned_data['billing_city'],
                
            )
            
            order.billing_address = address
            
        order.save()
        
        messages.info(self.request, 'Thank you for your order')
        
        return super(CheckoutView, self).form_valid(form)
    
    
    def get_form_kwargs(self):
        
        kwargs = super(CheckoutView, self).get_form_kwargs()
        
        kwargs['user_id'] = self.request.user.id
        
        return kwargs
        
    
    def get_context_data(self, **kwargs):
        
        context = super(CheckoutView, self).get_context_data(**kwargs)
        
        context ['order'] = get_or_set_order_session(self.request)
        
        return context
    
    

class PaymentView(generic.TemplateView):
    
    template_name = 'cart/payment.html'
    
    def get_context_data(self, **kwargs):
        
        context = super(PaymentView, self).get_context_data(**kwargs)
        
        context ['PAYPAL_CLIENT_ID'] = settings.PAYPAL_CLIENT_ID
        
        context['order'] = get_or_set_order_session(self.request)
        
        context['CALLBACK_URL']= reverse('cart:thank-you')
        
        return context
    
class ConfirmOrderView(generic.View):
    
    def post(self, request, *args, **kwargs):
        
        body = json.loads(request.body)
        print(body)
        
        order = get_or_set_order_session(request)
        
        payment = Payment.objects.create(
            order= order,
            successful = True,
            raw_response = json.dumps(body),
            amount = float(body["purchase_units"][0]["amount"]["value"]) ,
            payment_method = 'PayPal'
            
        )
        
        order.ordered = True 
        order.ordered_date = datetime.date.today()
        order.saved()
        
        return JsonResponse({'data': "success"})
    
class ThankYouView(generic.TemplateView):
    
    template_name = 'cart/thank-you.html'

templates/cart/cart.html
{% extends 'base.html' %} 

{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}" >Home</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-block" > Cart </strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row mb-5">

            <div class="col-md-12 text-center">
                <div class="site-block-table">
                    <table>
                        <thead>
                            <tr>                            
                                <th>Imagen</th>
                                <th>Product</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Total</th>
                                <th>Actions</th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for item in order.items.all %}
                                <tr>
                                    <td class="prosuct-thumbnail" >
                                        <img src="{{ item.product.image.url }}" class="img-fluid" >
                                    </td>

                                    <td class="product-name">
                                        <h2 class="h5 text-black">{{ item.product.title }}</h2>
                                        <small>Size: {{ item.size.name }} </small>
                                        <small>Colour: {{ item.colour.name }} </small>
                                    </td>

                                    <td class="text-center" >${{ item.product.get_price }}</td>
                                    <td>
                                        <div class="input-group mb-3" style="max-width: 120px;">
                                            <div class="input-group-pretend">
                                                <a href="{% url 'cart:decrease-quantity' item.id %}" class="btn btn-outline-primary" >
                                                    &minus;
                                                </a>
                                            </div>

                                            <input type="text" class="form-control text-center " 
                                                value="{{ item.quantity }}" >

                                            <div class="input-group-pretend">
                                                <a href="{% url 'cart:increase-quantity' item.id %}" class="btn btn-outline-primary" >
                                                    &plus;
                                                </a>
                                            </div>
                                        </div>
                                    </td>

                                    <td>
                                        ${{ item.get_total_item_price }}
                                    </td>

                                    <td>
                                        <a href="{% url 'cart:remove-from-cart' item.id %}" class="btn btn-primary btn-sm" >X</a>
                                    </td>
                                    
                                </tr>

                                {% empty %}
                                <tr>
                                    <td colspan="6" >
                                        There are no items in your cart. <a href="{% url 'cart:product-list' %}" > Continue shopping </a>
                                    </td>
                                </tr>

                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>


        </div>

        {% if order.items.count > 0 %}
            <div class="row">
                <div class="col-md-6">
                    <div class="row mb-5 ">
                        <div class="col-md-12">
                            <a class="btn btn-outline-primary btn-sm btn-block" 
                            href="{% url 'cart:product-list' %}"> Continue shopping </a>
                        </div>
                    </div>
                </div>

                <div class="col-md-6 pl-5">
                    <div class="row justify-content-end ">
                        <div class="col-md-12" > 
                            <div class="row">
                                <div class="col-md-12 text-right border-bottom mb-5">
                                    <h3 class="text-black h4 text-uppercase "  > Cart Totals </h3>
                                </div>
                            </div> 

                            <div class="row  mb-3">
                                <div class="col-md-6">
                
                                    <span class="text-black" >Subtotal</spnan>
                                </div>

                                <div class="col-md-6 text-right">
                                    <strong class="text-black" >$ {{ order.get_subtotal }} </strong>
                                </div>
                
                            </div>
                            
                            <div class="row  mb-5">
                                <div class="col-md-6">
                
                                    <span class="text-black" >Total</spnan>
                                </div>

                                <div class="col-md-6 text-right">
                                    <strong class="text-black" >${{ order.get_total  }}</strong>
                                </div>
                
                            </div>

                            <div class="row  ">
                                <div class="col-md-12">
                                    <a href="{% url 'cart:checkout' %}" class="btn btn-warning btn-lg py-3 btn-block " >Proceed to checkout</a>
                                </div>
                
                            </div>

                        </div>
                    </div>
                </div>

            </div>
        {% endif %}
        
        

    </div>
</div>

{% endblock %}

templates/cart/payment.html
{% extends 'base.html' %}

{% block content %}

<style>
    .lds-roller {
        display: inline-block;
        position: relative;
        width: 80px;
        height: 80px;
      }
      .lds-roller div {
        animation: lds-roller 1.2s cubic-bezier(0.5, 0, 0.5, 1) infinite;
        transform-origin: 40px 40px;
      }
      .lds-roller div:after {
        content: " ";
        display: block;
        position: absolute;
        width: 7px;
        height: 7px;
        border-radius: 50%;
        background: #fff;
        margin: -4px 0 0 -4px;
      }
      .lds-roller div:nth-child(1) {
        animation-delay: -0.036s;
      }
      .lds-roller div:nth-child(1):after {
        top: 63px;
        left: 63px;
      }
      .lds-roller div:nth-child(2) {
        animation-delay: -0.072s;
      }
      .lds-roller div:nth-child(2):after {
        top: 68px;
        left: 56px;
      }
      .lds-roller div:nth-child(3) {
        animation-delay: -0.108s;
      }
      .lds-roller div:nth-child(3):after {
        top: 71px;
        left: 48px;
      }
      .lds-roller div:nth-child(4) {
        animation-delay: -0.144s;
      }
      .lds-roller div:nth-child(4):after {
        top: 72px;
        left: 40px;
      }
      .lds-roller div:nth-child(5) {
        animation-delay: -0.18s;
      }
      .lds-roller div:nth-child(5):after {
        top: 71px;
        left: 32px;
      }
      .lds-roller div:nth-child(6) {
        animation-delay: -0.216s;
      }
      .lds-roller div:nth-child(6):after {
        top: 68px;
        left: 24px;
      }
      .lds-roller div:nth-child(7) {
        animation-delay: -0.252s;
      }
      .lds-roller div:nth-child(7):after {
        top: 63px;
        left: 17px;
      }
      .lds-roller div:nth-child(8) {
        animation-delay: -0.288s;
      }
      .lds-roller div:nth-child(8):after {
        top: 56px;
        left: 12px;
      }
      @keyframes lds-roller {
        0% {
          transform: rotate(0deg);
        }
        100% {
          transform: rotate(360deg);
        }
      }
</style>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

            <div class="alert alert-success" role="alert" id="alertSuccess" style="display:none;">
                Your payment was successful!
            </div>

            <div class="alert alert-danger" role="alert" id="alertFailure" style="display:none;">
                Your payment failed. Please try again.
            </div>

            <div class="text-center py-3">

                <div class="lds-roller" style="margin:auto; display:none;"  id="loader">
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
            </div>

            

            <div id="paymentInfo">
                <p>Order Total: <strong>$ {{ order.get_total }}</strong></p>
                <h4>Select a payment method </h4>
                <div id="paypal-button-container"></div>
            </div>

            

        </div>
    </div>
</div>


{% endblock %}

{% block scripts %}

    <script 
        src="https://www.paypal.com/sdk/js?&client-id={{ PAYPAL_CLIENT_ID }}">
    </script>

    <script> 

        const loader= document.getElementById('loader');

        const paymentInfo = document.getElementById('paymentInfo');

        function toggleLoader(on){
            loader.style.display = on ? 'block' : 'none';
            paymentInfo.style.display = on ? 'none' : 'block';
        }

        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');
        
        function sendOrderConfirmed(){
            return fetch(" {% url 'cart:confirm-order' %}", {
                method: 'POST',
                body: JSON.stringify(details),
                headers: {
                    "Content-Type": "application/json",
                    "X-CSRFToken": csrftoken
                }
            } )
        }
        
        paypal.Buttons({
        createOrder: function(data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: '{{ order.get_total }}' // Can reference variables or functions. Example: `value: document.getElementById('...').value`
                        }
                    }]
                });
            },

            onApprove: function(data, actions) {
                toggleLoader(true);
                return actions.order.capture().then(function(detalis) {
                    sendOrderConfirmed(details).then(res => {

                        toggleLoader(false);
                        const alertSuccess = document.getElementById('alertSuccess');
                        alertSuccess.style.display = 'block';
                       
                        setTimeout(function() => {
                            window.location.replace("{{ CALLBACK_URL }}");
                        }, 3000 );
                    })
                })
                .catch(err => {
                    const alertFailure = document.getElementById('alertFailure');
                    alertFailure.style.display = 'block';
                })
                .finally(() => toggleLoader(false));
            }
            
        }).render('#paypal-button-container'); </script>
    </script>

{% endblock %}

templates/cart/product_detail.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}

{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}" >Home</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-block" > {{ product.title }} </strong>
            </div>

        </div>

    </div>
</div>


<div class="site-section">
    <div class="container">
        <div class="row mb-5">

            <div class="col-md-6">
                <a> <img src="{{ product.image.url }}" class="img-fluid" > </a>
            </div>

            
                <div class="col-md-6 mb-4 " data-aos= 'fade-up' >
                    <h2 class="text-black" > {{ product.title }} </h2> 
                    <p> {{ product.description }} </p>

                    <form method="POST">
                        {% csrf_token %}

                        {{ form|crispy }}

                        <button type="submit" class="btn btn-sm btn-primary  buy-now"> Add to Cart </button>

                    </form>
                </div>

        </div>
    </div>
</div>

{% endblock %}

templates/cart/thank-you.html
{% extends 'base.html' %}

{% block content %}

<h2>Thanks for your order!</h2>

{% endblock %}