app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home' ),
    path('contact/', views.ContactView.as_view(), name="contact" ),
    path('cart/', include('cart.urls', namespace="cart" )),
    path('accounts/', include('allauth.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='summary'),
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('increase-quantity/<pk>/', views.IncreaseQuantityView.as_view(), name="increase-quantity"  ),
    path('decrease-quantity/<pk>/', views.DecreaseQuantityView.as_view(), name="decrease-quantity"  ),
    path('remove-from-cart/<pk>/', views.RemoveFromCartView.as_view(), name="remove-from-cart"  ),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('thank-you/', views.ThankYouView.as_view(), name='thank-you' ),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order' ), 
]

templates/base.html
{% load static %}
{% load cart_template_tags %}

<!doctype html>
<html lang="es" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title> Django {% block title %} {% endblock %}  </title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/cover/">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">



  </head>
<body>
    
    <div class="site-wrap">
        <header class="site-navbar" role="banner" >
            <div class="site-navbar-top" >
                <div class="container" > 
                    <div class="row align-items-center" >
                        <div class="col-6 col-md-8 mb-3 mb-md-0 col-md-4 order-1 order-md-2" >
                            <div>
                                <a href="{% url 'home' %}">
                                    LOGO 
                                </a>
                            </div>
                        </div>

                        <div class="col-6 col-md-4 order-3 order-md-3 text-right" >
                            <div class="site-top-icons">
                                <ul>

                                    <li>
                                        {% if request.user.is_authenticated %}
                                        <a href="/"> <span> <i class="fas fa-user" ></i> user </span> </a>
                                        {% else %}  
                                            <a href="/" > <span> <i class="fas fa-sign-in-alt" ></i> </span></a>
                                        {% endif %}
                                    </li>

                                    <li>
                                        <a href="{% url 'cart:summary' %}" class="site-cart" >  
                                            <span> <i class="fas fa-shopping-cart" > </i> cart </span>
                                            <span class="count" > {{ request|cart_item_count }} </span>
                                        </a>
                                    </li>

                                    <li class="d-inline-block d-md-none ml-md-0">
                                        <a href="#" class="site-menu-toggle js-menu-toggle" > 
                                            <span> <i class="fas fa-bars"></i> </span>
                                        </a>
                                    </li>
                                </ul>

                            </div>
                            
                        </div>

                    </div>
                </div>
           
            </div>

            {% include 'navbar.html' %}
            {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    <span class="alert-inner--icon"> <i class="ni ni-like-2" > </i>  </span>
                    <span class="alert-inner--text" > {{ message }} </span>

                    <button type="button" class="close" data-dismiss="alert" aria-label="Close" >
                        <span aria-hidden="true" > &times; </span>
                    </button>
                </div>
            {% endfor %}
            {% endif %}

        </header>

        {% block content %} {% endblock %}

        {% include 'footer.html' %}

    </div>

    {% include 'scripts.html' %}

    {% block scripts %} {% endblock %}
    
  </body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Home</a> 
                <span class="mx-2 mb-0">/</span>
                <strong class="text-block" >Contact</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col md-7">
                <h2 class="h3 mb-3 text-black">Get in touch</h2>
            </div>

            <div class="col md-7">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}

                    <input type="submit" class="btn btn-primary btn-lg btn-block " value="submit me" />

                </form>
            </div>

        </div>
    </div>
</div>

{% endblock %}

templates/footer.html
<footer class="site-footer border-top">
    <div class="container" >
        <div class="row text-center" > 
            <div class="col-md-12" >
                <p>
                    Copyright &copy;
                    <script> document.write(new Date().getFullYear()); </script>
                    All right reserved | this website is made with <i class="fa fas-heart" >  </i>
                </p>
            </div>
        </div>
    </div>

</footer>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="site-blocks-cover" style="background-image: url({% static 'images/hero2.jpg' %}); " data-aos="fade" >
    <div class="container">
        <div class="row">
            <div class="col-md-4 pt-5 pt-md-0" >
            </div>
            
        </div>
                
    </div>
    
</div>

{% endblock %}

templates/navbar.html
<nav class="site-navigation text-right text-md-center" roles="navigation">
    <div class="container">
        <ul class="site-menu js-clone-nav d-none d-md-block " style="padding:0;"  >
            <li><a href="/">Home</a></li>
            <li><a href="{% url 'cart:product-list' %}">Shop</a></li>
            <li><a href="{% url 'contact' %}">Contact</a></li>
            {% if request.user.is_staff %}
            <li><a href="/" >Staff</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/scripts.html
{% load static %}